name: modul_8
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.10
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  get: ^4.6.3
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5
  file_picker: ^4.6.0
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.16
  cached_network_image: ^3.2.0
  flutter_icons: ^1.1.0
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1
  device_info_plus: ^3.2.3
  http: ^0.13.4
  flutter_slidable: ^1.3.1
  scoped_model: ^1.1.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
